global:
  scrape_interval: 15s  # Default scrape interval 

scrape_configs:
  - job_name: 'custom_metrics'
    scrape_interval: 2s  # Setting the scrape interval to 2 seconds
    static_configs:
      - targets: ['localhost:18000']  # The address where application exposes metrics
